# Generated by Django 4.2.3 on 2023-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
