# Generated by Django 4.2.3 on 2023-08-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
