# Generated by Django 4.2.3 on 2023-08-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='userId',
        ),
    ]
