# Generated by Django 4.2.3 on 2023-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_product_cart_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.TextField(max_length=25, null=True, unique=True),
        ),
    ]
